from reportlab.lib.colors import HexColor

BLU_CONF_HEX = "#1170d0"
BLU_CONF = HexColor(BLU_CONF_HEX)
GRIGIO_TESTO = HexColor("#050F1B")

PAGINE = [
    "1. Anagrafica",
    "2. Servizi tradizionali",
    "3. Clienti e Mercati",
    "4. Tecnologie",
    "5. Risorse Umane",
    "6. Acquisti",
    "7. Logistica",
    "8. Realizzazione prodotto / servizio",
    "9. Sostenibilita ambientale",
    "Digital Intensity Index",
    "Report finale",
]

SCALA_MATURITA = [
    "Attraverso consulenti/fornitori esterni o non sono realizzate",
    "Prevalentemente in modo non digitale",
    "In modo digitale senza integrazione con le altre funzioni aziendali",
    "In modo digitale con dati condivisi automaticamente con altre funzioni",
    "In modo digitale con integrazione completa e utilizzo automatico dei dati per decisioni e misurazione delle prestazioni",
]

MAPPA_SCALA_MATURITA = {
    SCALA_MATURITA[0]: 1,
    SCALA_MATURITA[1]: 2,
    SCALA_MATURITA[2]: 3,
    SCALA_MATURITA[3]: 4,
    SCALA_MATURITA[4]: 5,
}

MAPPA_PROCESSI_DECISIONALI = {
    "Esperienza e intuizione": 1,
    "Osservazione di opportunita e concorrenti": 2,
    "Strategia supportata da dati di mercato": 3,
    "Strategia supportata da dati di mercato e dati interni": 4,
    "Strategia proattiva basata su analisi continua dei dati": 5,
}

MAPPA_GESTIONE_CLIENTI = {
    "Non esiste una gestione strutturata": 1,
    "Informazioni sparse (email, rubriche, fogli Excel)": 2,
    "Database clienti organizzato": 3,
    "Software gestionale o CRM": 4,
    "Sistema CRM integrato con altri sistemi aziendali": 5,
}

MAPPA_USO_DATI_CLIENTI = {
    "Non vengono raccolti o analizzati": 1,
    "Raccolti ma usati raramente": 2,
    "Utilizzati per alcune decisioni commerciali": 3,
    "Analizzati regolarmente": 4,
    "Utilizzati in modo sistematico per strategie commerciali": 5,
}

MAPPA_STRATEGIA_DIGITALE = {
    "No": 1,
    "In fase di definizione": 2,
    "Si, ma non formalizzata": 3,
    "Si, formalizzata": 4,
    "Si, formalizzata e monitorata con KPI": 5,
}

MAPPA_RESPONSABILE_DIGITALE = {
    "No": 1,
    "No, ma sara nominato": 3,
    "Si": 5,
}

MAPPA_FORMAZIONE_40 = {
    "Non valutata": 1,
    "Prevista entro 12 mesi": 3,
    "Gia svolta": 5,
}

MAPPA_TECNOLOGIE = {
    "Non presente": 0,
    "Previsto entro 3 anni": 0.5,
    "Presente": 1,
}

MAPPA_RD = {
    "Nessuna attivita di R&D": 1,
    "Attivita occasionali non strutturate": 2,
    "Attivita strutturate senza budget": 3,
    "Attivita strutturate con budget": 4,
    "Funzione R&D formalizzata con KPI": 5,
    "Nessuna": 1,
    "Figura informale": 2,
    "Figura formalmente nominata": 3,
    "Team interno dedicato": 4,
    "Team interno + collaborazioni esterne": 5,
    "Nessun metodo": 1,
    "Intuizioni informali": 2,
    "Analisi di mercato": 3,
    "Analisi dati interni/esterni": 4,
    "Processi strutturati (design thinking, test pilota)": 5,
    "Nessun supporto digitale": 1,
    "Strumenti di base": 2,
    "Software specialistici (CAD, simulazione, PLM)": 3,
    "Integrazione con sistemi aziendali": 4,
    "Uso avanzato di dati e AI": 5,
}

TECNOLOGIE_OPZIONI = [
    "AI (ChatGPT, Gemini, ...)",
    "AI (LLM locali)",
    "AI (Integrazione Agenti AI)",
    "Blockchain",
    "Robotica",
    "Stampa 3D",
    "AR/VR",
    "Simulazione",
    "IoT",
    "Cloud",
    "Cybersicurezza",
    "Big Data",
    "CAD/CAM",
    "E-commerce",
    "Pagamenti digitali",
    "EDI",
    "Geolocalizzazione",
    "ERP",
    "WMS",
    "MES",
    "CRM/SCM/PLM",
    "RFID",
    "System integrator",
    "Altro",
]

ORDINE_CHIAVI_REPORT = [
    "ragione_sociale",
    "forma_societaria",
    "piva_cf",
    "email_principale",
    "comune",
    "provincia",
    "regione",
    "telefono",
    "nome_compilatore",
    "cognome_compilatore",
    "ruolo_compilatore",
    "sedi",
    "codice_ateco",
    "settore",
    "addetti",
    "fatturato",
    "mercato",
    "note_anagrafica",
    "contabilita_finanza",
    "strumenti_amministrativi",
    "processi_decisionali",
    "gestione_contabilita",
    "confartigianato_servizio",
    "note_contabilita",
    "gestione_clienti",
    "strumenti_clienti",
    "presenza_digitale",
    "uso_dati_clienti",
    "analisi_mercato",
    "marketing",
    "vendite",
    "assistenza_post_vendita",
    "note_clienti_mercati",
    "sistemi_informativi",
    "ricerca_sviluppo",
    "strategia_digitale",
    "proprieta_intellettuale",
    "tecnologie",
    "rd_governance",
    "rd_responsabile",
    "rd_metodo",
    "rd_digitale",
    "rd_collaborazioni",
    "rd_progetti_futuri",
    "note_tecnologie",
    "gestione_personale",
    "responsabile_digitale",
    "formazione_40",
    "temi_formazione",
    "figure_formate",
    "note_risorse_umane",
    "gestione_fornitori",
    "gestione_acquisti",
    "valutazione_fornitori",
    "note_acquisti",
    "logistica_applicabile",
    "logistica_interna",
    "logistica_esterna",
    "tracciabilita",
    "note_logistica",
    "produzione_servizi",
    "controllo_qualita",
    "manutenzione",
    "note_realizzazione",
    "sostenibilita_digitale",
    "finalita_sostenibilita",
    "risultati_sostenibilita",
    "risultati_sostenibilita_altro",
    "note_sostenibilita",
    "servizi_cciaa",
    "servizi_cciaa_altro",
    "interesse_servizi",
    "interesse_servizi_altro",
    "note_conclusione",
    "dii_addetti_connessi",
    "dii_ai",
    "dii_banda_larga",
    "dii_analisi_dati",
    "dii_cloud_base",
    "dii_cloud_intermedio_avanzato",
    "dii_social_media",
    "dii_erp",
    "dii_crm",
    "dii_due_social",
    "dii_vendite_online_1",
    "dii_vendite_b2c",
]

ETICHETTE_RISPOSTE = {
    "ragione_sociale": "Ragione sociale",
    "forma_societaria": "Forma societaria",
    "piva_cf": "Codice fiscale / Partita IVA",
    "email_principale": "Email principale",
    "comune": "Comune",
    "provincia": "Provincia",
    "regione": "Regione",
    "telefono": "Telefono",
    "nome_compilatore": "Nome compilatore",
    "cognome_compilatore": "Cognome compilatore",
    "ruolo_compilatore": "Ruolo compilatore",
    "sedi": "Sedi / stabilimenti",
    "codice_ateco": "Codice ATECO",
    "settore": "Settore prevalente",
    "addetti": "Numero addetti",
    "fatturato": "Fatturato ultimo anno",
    "mercato": "Tipo di mercato",
    "note_anagrafica": "Note aggiuntive - Anagrafica",
    "contabilita_finanza": "Gestione contabilita e finanza",
    "strumenti_amministrativi": "Strumenti digitali per la gestione amministrativa",
    "processi_decisionali": "Base principale dei processi decisionali",
    "gestione_contabilita": "Gestione della contabilita aziendale",
    "confartigianato_servizio": "Servizi gestiti da Confartigianato",
    "note_contabilita": "Note aggiuntive - Contabilita e Finanza",
    "gestione_clienti": "Gestione delle informazioni sui clienti",
    "strumenti_clienti": "Strumenti utilizzati per gestire i clienti",
    "presenza_digitale": "Canali digitali utilizzati verso il mercato",
    "uso_dati_clienti": "Utilizzo dei dati dei clienti",
    "analisi_mercato": "Monitoraggio del mercato e dei concorrenti",
    "marketing": "Marketing",
    "vendite": "Vendite",
    "assistenza_post_vendita": "Assistenza post vendita",
    "note_clienti_mercati": "Note aggiuntive - Clienti e Mercati",
    "sistemi_informativi": "Livello di digitalizzazione e integrazione dei sistemi informativi aziendali",
    "ricerca_sviluppo": "Livello generale delle attivita di ricerca, sviluppo e innovazione",
    "strategia_digitale": "Strategia digitale o di innovazione formalizzata",
    "proprieta_intellettuale": "Proprieta intellettuale posseduta dall'impresa",
    "tecnologie": "Tecnologie adottate o previste",
    "rd_governance": "Livello di strutturazione delle attivita di R&D",
    "rd_responsabile": "Responsabilita R&D",
    "rd_metodo": "Metodo di generazione e selezione delle idee",
    "rd_digitale": "Utilizzo di strumenti digitali nelle attivita di ricerca e sviluppo",
    "rd_collaborazioni": "Collaborazioni R&D",
    "rd_progetti_futuri": "Progetti e idee future in ambito R&D",
    "note_tecnologie": "Note aggiuntive - Tecnologie e R&D",
    "gestione_personale": "Digitalizzazione dei processi di gestione del personale",
    "responsabile_digitale": "Responsabile trasformazione digitale",
    "formazione_40": "Formazione Impresa 4.0",
    "temi_formazione": "Temi formazione",
    "figure_formate": "Figure coinvolte",
    "note_risorse_umane": "Note aggiuntive - Risorse Umane",
    "gestione_fornitori": "Gestione fornitori",
    "gestione_acquisti": "Gestione acquisti",
    "valutazione_fornitori": "Valutazione fornitori",
    "note_acquisti": "Note aggiuntive - Acquisti",
    "logistica_applicabile": "Applicabilita della logistica",
    "logistica_interna": "Logistica interna",
    "logistica_esterna": "Logistica esterna",
    "tracciabilita": "Tracciabilita dei materiali e gestione del magazzino",
    "note_logistica": "Note aggiuntive - Logistica",
    "produzione_servizi": "Produzione o erogazione del servizio",
    "controllo_qualita": "Controllo qualita",
    "manutenzione": "Manutenzione",
    "note_realizzazione": "Note aggiuntive - Realizzazione prodotto / servizio",
    "sostenibilita_digitale": "Adozione tecnologie per sostenibilita",
    "finalita_sostenibilita": "Finalita",
    "risultati_sostenibilita": "Risultati",
    "risultati_sostenibilita_altro": "Specificare altro - risultati sostenibilita",
    "note_sostenibilita": "Note aggiuntive - Sostenibilita ambientale",
    "dii_addetti_connessi": "DII 1 - Addetti connessi alla rete oltre il 50%",
    "dii_ai": "DII 2 - Utilizzo di Intelligenza Artificiale",
    "dii_banda_larga": "DII 3 - Connessione fissa >= 30 Mbit/s",
    "dii_analisi_dati": "DII 4 - Analisi dei dati per previsioni e supporto decisionale",
    "dii_cloud_base": "DII 5 - Acquisto di servizi cloud computing",
    "dii_cloud_intermedio_avanzato": "DII 6 - Acquisto di servizi cloud intermedi o sofisticati",
    "dii_social_media": "DII 7 - Utilizzo di almeno un social media",
    "dii_erp": "DII 8 - Utilizzo di ERP",
    "dii_crm": "DII 9 - Disponibilita di CRM",
    "dii_due_social": "DII 10 - Utilizzo di almeno due social media",
    "dii_vendite_online_1": "DII 11 - Vendite online >= 1% dei ricavi",
    "dii_vendite_b2c": "DII 12 - Vendite web e quota B2C",
}
